// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS2OYNtIBD5A_AQFXAHRdSieiZFV-Mumg',
    appId: '1:990752512202:web:1e15c8cb716cfb1a183c33',
    messagingSenderId: '990752512202',
    projectId: 'clinic-4cc38',
    authDomain: 'clinic-4cc38.firebaseapp.com',
    storageBucket: 'clinic-4cc38.firebasestorage.app',
    measurementId: 'G-THLJS9ZN4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMA9vaUd21kcPvVEybdF8ja35npHo917Q',
    appId: '1:990752512202:android:c19f8e52cce6857c183c33',
    messagingSenderId: '990752512202',
    projectId: 'clinic-4cc38',
    storageBucket: 'clinic-4cc38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz9z3Kjmgf6q-54Q16vTsRP_UZ_CKkWko',
    appId: '1:990752512202:ios:283374c575e23826183c33',
    messagingSenderId: '990752512202',
    projectId: 'clinic-4cc38',
    storageBucket: 'clinic-4cc38.firebasestorage.app',
    iosBundleId: 'com.example.clinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz9z3Kjmgf6q-54Q16vTsRP_UZ_CKkWko',
    appId: '1:990752512202:ios:283374c575e23826183c33',
    messagingSenderId: '990752512202',
    projectId: 'clinic-4cc38',
    storageBucket: 'clinic-4cc38.firebasestorage.app',
    iosBundleId: 'com.example.clinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS2OYNtIBD5A_AQFXAHRdSieiZFV-Mumg',
    appId: '1:990752512202:web:75f0e09add7616c1183c33',
    messagingSenderId: '990752512202',
    projectId: 'clinic-4cc38',
    authDomain: 'clinic-4cc38.firebaseapp.com',
    storageBucket: 'clinic-4cc38.firebasestorage.app',
    measurementId: 'G-7B476M75K1',
  );

}