// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDcf4_owo9gur0c_pWCUfKZ8eiYE2kAz0c",
    authDomain: "clinic-appointment-403a3.firebaseapp.com",
    projectId: "clinic-appointment-403a3",
    storageBucket: "clinic-appointment-403a3.firebasestorage.app",
    messagingSenderId: "762047191126",
    appId: "1:762047191126:web:69962d3fd850380593c3f7",
    measurementId: "G-6LR5Y6Z16F",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKNkDBmWWjvcc-MN32QqtHlvrewntQ5ko',
    appId: '1:762047191126:android:15dd4d9d21319ddd93c3f7',
    messagingSenderId: '762047191126',
    projectId: 'clinic-appointment-403a3',
    storageBucket: 'clinic-appointment-403a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-kwr4yMG1AAabnylHqAMTmsnhxc6tqts',
    appId: '1:762047191126:ios:0f4ff91d1c2e45b993c3f7',
    messagingSenderId: '762047191126',
    projectId: 'clinic-appointment-403a3',
    storageBucket: 'clinic-appointment-403a3.firebasestorage.app',
    iosBundleId: 'com.example.clinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-kwr4yMG1AAabnylHqAMTmsnhxc6tqts',
    appId: '1:762047191126:ios:0f4ff91d1c2e45b993c3f7',
    messagingSenderId: '762047191126',
    projectId: 'clinic-appointment-403a3',
    storageBucket: 'clinic-appointment-403a3.firebasestorage.app',
    iosBundleId: 'com.example.clinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcf4_owo9gur0c_pWCUfKZ8eiYE2kAz0c',
    appId: '1:762047191126:web:d11a0d85e8e2132293c3f7',
    messagingSenderId: '762047191126',
    projectId: 'clinic-appointment-403a3',
    authDomain: 'clinic-appointment-403a3.firebaseapp.com',
    storageBucket: 'clinic-appointment-403a3.firebasestorage.app',
    measurementId: 'G-FZZEQVJQ14',
  );
}
