// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsQhWd6AgOqla5zTVrUmGcIgk8NQadsr4',
    appId: '1:376230310822:web:85a4d7d4e779af2a3c5567',
    messagingSenderId: '376230310822',
    projectId: 'clinicalappointmentapp-4edb5',
    authDomain: 'clinicalappointmentapp-4edb5.firebaseapp.com',
    storageBucket: 'clinicalappointmentapp-4edb5.firebasestorage.app',
    measurementId: 'G-ETSC1EDC32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7RCUXUT587mdjE_EWYEPYj6GGfkaC9HA',
    appId: '1:376230310822:android:9758ae13ee0d27313c5567',
    messagingSenderId: '376230310822',
    projectId: 'clinicalappointmentapp-4edb5',
    storageBucket: 'clinicalappointmentapp-4edb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGz0rgb5RTw0XCtc8MkUp-lAE-Kbadys8',
    appId: '1:376230310822:ios:fb202d2bb99983743c5567',
    messagingSenderId: '376230310822',
    projectId: 'clinicalappointmentapp-4edb5',
    storageBucket: 'clinicalappointmentapp-4edb5.firebasestorage.app',
    iosBundleId: 'com.example.clinicAppointmentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGz0rgb5RTw0XCtc8MkUp-lAE-Kbadys8',
    appId: '1:376230310822:ios:fb202d2bb99983743c5567',
    messagingSenderId: '376230310822',
    projectId: 'clinicalappointmentapp-4edb5',
    storageBucket: 'clinicalappointmentapp-4edb5.firebasestorage.app',
    iosBundleId: 'com.example.clinicAppointmentSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsQhWd6AgOqla5zTVrUmGcIgk8NQadsr4',
    appId: '1:376230310822:web:51286413f584fe213c5567',
    messagingSenderId: '376230310822',
    projectId: 'clinicalappointmentapp-4edb5',
    authDomain: 'clinicalappointmentapp-4edb5.firebaseapp.com',
    storageBucket: 'clinicalappointmentapp-4edb5.firebasestorage.app',
    measurementId: 'G-X8ZB5G775C',
  );
}
